### ISSUE TITLE
'time' was not declared in this scope

### ISSUE THREAD

**Issue by Salymz** [teaandcode/TestChain#4]
l\blocktuto.cpp:11: erreur : 'time' was not declared in this scope
     _tTime = time(nullptr);
                          ^

**Comment by knasher** [comment]
blocktuto.cpp is not a file in the project, you should try cloning the repo and compiling before making changes; here's the command to compile the project:

```
gcc -lstdc++ \
    -o TestChain \
    -std=c++11 \
    -stdlib=libc++ \
    -x c++ \
    main.cpp Block.cpp Blockchain.cpp sha256.cpp
```
